### ISSUE TITLE
Define any own gate as Liqui|>

### ISSUE THREAD

**Issue by EnginSahinCE** [Microsoft/Quantum#24]
We could define our own gates at the Liqui|> library (for example as follows). Can we define our gates at MS Quantum Dev Kit?  If we can define it, how do we define it  at MS Quantum Dev Kit?

`any gate (as defined with any CSMat)

    let GT (qs:Qubits) =
        let gate =        
            new Gate(
               Name = "GT",
                Help = "GT",
                Mat = CSMat(2,[0,0,1.,0.;0,1,1.,0.;1,0,0.,0.;1,1,0.,0.])
            )
        gate.Run qs
`

**Comment by martinquantum** [comment]
Thanks for your question. By design, Q# does not support the concept of user defined gates, say from the matrix coefficients of a unitary gate. The intent is to provide a set of primitive gates in the standard library which are then implemented by the underlying abstract machine. All other operations have to be expressed in terms of these primitive gates (or of course in terms of other library functions). 

That being said, if you want to, say, specify a single qubit gate by way of the matrix entries (that are given, say, by floating point representations of the real and imaginary parts), one way to do this is to define a new ```operation``` to wrap said gate. Inside the operation, you can use ```RFrac``` or ```R``` operations to rotate the Bloch sphere around Pauli axes by given angles. In case of single qubit gates the angles could be computed by an Euler angle decomposition of the initial matrix, but other methods might be available as well.
