### ISSUE TITLE
Issue using NWChem Docker image on Mac

### ISSUE THREAD

**Issue by christopherkang** [microsoft/Quantum#395]
**Describe the bug**
When using the instructions [here](https://docs.microsoft.com/en-us/quantum/user-guide/libraries/chemistry/samples/end-to-end) to convert NWChem output to Broombridge, the program fails with numerous error messages when running "Convert-NWChemToBroombridge"

I believe the issue is on this line: 
https://github.com/microsoft/Quantum/blob/master/utilities/InvokeNWChem.psm1#L138

Instead `mkdir --Path`, I believe the line should read `mkdir -p` - after changing the line, my code worked without problems.

**To Reproduce**
Follow the instructions at the link provided above

**Expected behavior**
The Powershell command outputs the YAML without problems :) 

**Screenshots**

**System information**
 - OS: MacOS 10.15.5

**Additional context**

**Comment by cgranade** [comment]
Thanks for raising this, @christopherkang. I suspect what happened is that some versions of PowerShell set up `mkdir` as an alias automatically while some don't, such that changing this line to use `New-Item -Type Directory` instead of `mkdir` should allow this script to work both on Unix-style systems (where `mkdir -p` is a great workaround!) and Windows-style systems where `mkdir -p` may not be available.

**Comment by christopherkang** [comment]
I'm glad there's a straightforwards fix, @cgranade! Grateful for your fast and detailed responses 🚀
