### ISSUE TITLE
User-defined quantum gate in Q#

### ISSUE THREAD

**Issue by wengrs** [Microsoft/Quantum#44]
User-defined quantum gate is important in research. But Q# no support it.

**Comment by martinquantum** [comment]
Thanks for your question. By design, Q# does not support the concept of user defined gates, say from the matrix coefficients of a unitary gate. The intent is to provide a set of primitive gates in the standard library which are then implemented by the underlying abstract machine. All other operations have to be expressed in terms of these primitive gates (or of course in terms of other library functions). 

That being said, if you want to, say, specify a single qubit gate by way of the matrix entries (that are given, say, by floating point representations of the real and imaginary parts), one way to do this is to define a new ```operation``` to wrap said gate. Inside the operation, you can use ```RFrac``` or ```R``` operations to rotate the Bloch sphere around Pauli axes by given angles. In case of single qubit gates the angles could be computed by an Euler angle decomposition of the initial matrix, but other methods might be available as well.

**Comment by wengrs** [comment]
Thanks
