### ISSUE TITLE
Why is the Deutsch-Jozsa sample uses 0 for constant function?

### ISSUE THREAD

**Issue by klenium** [Microsoft/Quantum#50]
The operation in Deutsch-Jozsa sample uses `return ForAll(IsResultZero, resultArray);`, and this operation's result is true when the function is constant. However, in every other literature they say if we measure 1 or -1, then the function is constant, and if 0, then it's balanced.

**Comment by tcNickolas** [comment]
You have to distinguish the amplitude of a certain state and the result of measuring that state.

Let's refer to the description in Nielsen and Chuang ([pages 34-36](https://books.google.com/books?id=-s4DEy7o-a0C)). ([Wikipedia](https://en.wikipedia.org/wiki/Deutsch%E2%80%93Jozsa_algorithm) agrees but in slightly different wording.)

If we do the math, before the measurements the _amplitude_ of the state |0...0> is (sum of (-1)^f(x))/2^n. 

If f(x) is constant and equals 0, the _amplitude_ of |0...0> is 1; if f(x) is constant and equals 1, the _amplitude_ of |0...0> is -1. In both those cases, since the overall state of the register has to have unit length, amplitudes of all other basis states are 0, so overall state of the system is |0...0> (+1 or -1 doesn't matter because it's a global phase and doesn't affect the outcome of measurements). If you measure it, the _result_ on each qubit is guaranteed to be `Zero`.

If f(x) is balanced, the _amplitude_ of the state |0...0> will be 0, which means you cannot measure all `Zero`s, at least one of the measurement results must be `One`.

This is exactly what concludes the description of the algorithm, and what the sample code implements.

Hope that helps!

**Comment by klenium** [comment]
I got it, thank you very much!
